package myasoedov.cs.storages.train;

public enum AttributeType {
    AGE, CONDITION, CARGO_WEIGHT, IS_OPEN, CURRENT_TEMPERATURE, NUMBER_IN_COMPOSITION, TRAIN_ID, NUMBER_OF_PASSENGERS,
    ELECTRIC_GRID_CONNECTION, VOLUME_OF_FUEL, WAGON_TYPE
}
